export const BUSINESS = {
  name: "RestOclair",
  legalName: "RestOclair",
  founder: "Thierry Bailleul",
  founderTitle: "Consultant en Hygiène et Sécurité Alimentaire",
  description:
    "Conseil en hygiène et sécurité alimentaire pour les professionnels partout en France. Urgence DDPP, audit hygiène, création PMS.",
  url: "https://restoclair.fr",
  email: "contact@restoclair.fr",
  phone: {
    display: "06 80 95 25 89",
    href: "tel:+33680952589",
    e164: "+33680952589",
  },
  address: {
    streetAddress: "10 Avenue du Général de Gaulle",
    postalCode: "80700",
    city: "Roye",
    region: "Hauts-de-France",
    country: "FR",
  },
  geo: {
    latitude: 49.6989,
    longitude: 2.7903,
  },
  openingHours: ["Mo-Fr 07:00-20:00", "Sa 08:00-18:00"],
  serviceAreas: [
    "Roye",
    "Amiens",
    "Compiègne",
    "Saint-Quentin",
    "Paris",
    "Île-de-France",
    "Hauts-de-France",
    "France entière",
  ],
  foundingYear: 2025,
  priceRange: "$$",
  sameAs: [],
};
